# Generated by Django 4.2.2 on 2023-07-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0002_contact_phone"),
    ]

    operations = [
        migrations.RenameField(model_name="contact", old_name="nom", new_name="name",),
    ]
